// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoemApp.Infrastructure.Data;

#nullable disable

namespace PoemApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123031223_AddPinyinToPoem")]
    partial class AddPinyinToPoem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PoemApp.Core.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("achievements");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EndIndex")
                        .HasColumnType("int");

                    b.Property<string>("HighlightText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("PoemId")
                        .HasColumnType("int");

                    b.Property<int>("StartIndex")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoemId");

                    b.HasIndex("UserId");

                    b.ToTable("annotations");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PoemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UploaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoemId");

                    b.HasIndex("UploaderId");

                    b.ToTable("audios");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.AudioRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AudioId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AudioId");

                    b.HasIndex("UserId");

                    b.ToTable("audioratings");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("longtext");

                    b.Property<int>("Dynasty")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.AuthorRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FromAuthorId")
                        .HasColumnType("int");

                    b.Property<int>("RelationshipType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("ToAuthorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromAuthorId");

                    b.HasIndex("ToAuthorId");

                    b.ToTable("authorrelationships");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Group")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Categories_Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("Group", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_Group_Name");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Poem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Annotation")
                        .HasColumnType("longtext");

                    b.Property<string>("Appreciation")
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Background")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pinyin")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Translation")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("poems");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.PoemCategory", b =>
                {
                    b.Property<int>("PoemId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("PoemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("poemcategories");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.PointsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("pointsrecords");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Annotation")
                        .HasColumnType("longtext");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PoemId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Translation")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PoemId");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.RecitationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualReviewTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ReminderSentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReviewRound")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserRecitationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRecitationId");

                    b.ToTable("recitationreviews");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QQId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("VipEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("VipStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WeChatId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RewardClaimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAchievement_User_Achievement");

                    b.ToTable("userachievements");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PoemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FavoriteTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "PoemId");

                    b.HasIndex("PoemId");

                    b.ToTable("userfavorites");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserQuoteFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FavoriteTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "QuoteId");

                    b.HasIndex("QuoteId");

                    b.ToTable("userquotefavorites");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserRecitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FirstRecitationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastReviewTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NextReviewTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PoemId")
                        .HasColumnType("int");

                    b.Property<int>("Proficiency")
                        .HasColumnType("int");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoemId");

                    b.HasIndex("UserId");

                    b.ToTable("userrecitations");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Annotation", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Poem", "Poem")
                        .WithMany("Annotations")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("Annotations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Audio", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Poem", "Poem")
                        .WithMany("Audios")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "Uploader")
                        .WithMany("Audios")
                        .HasForeignKey("UploaderId");

                    b.Navigation("Poem");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.AudioRating", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Audio", "Audio")
                        .WithMany("Ratings")
                        .HasForeignKey("AudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.AuthorRelationship", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Author", "FromAuthor")
                        .WithMany("Relationships")
                        .HasForeignKey("FromAuthorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.Author", "ToAuthor")
                        .WithMany()
                        .HasForeignKey("ToAuthorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FromAuthor");

                    b.Navigation("ToAuthor");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Category", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Poem", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Author", "Author")
                        .WithMany("Poems")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.PoemCategory", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Category", "Category")
                        .WithMany("Poems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.Poem", "Poem")
                        .WithMany("Categories")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.PointsRecord", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("PointsRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Quote", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Author", "Author")
                        .WithMany("Quotes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PoemApp.Core.Entities.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.RecitationReview", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.UserRecitation", "UserRecitation")
                        .WithMany("Reviews")
                        .HasForeignKey("UserRecitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRecitation");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserAchievement", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserFavorite", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Poem", "Poem")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserQuoteFavorite", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("QuoteFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserRecitation", b =>
                {
                    b.HasOne("PoemApp.Core.Entities.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoemApp.Core.Entities.User", "User")
                        .WithMany("Recitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Audio", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Author", b =>
                {
                    b.Navigation("Poems");

                    b.Navigation("Quotes");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Poems");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.Poem", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Audios");

                    b.Navigation("Categories");

                    b.Navigation("FavoritedBy");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Annotations");

                    b.Navigation("Audios");

                    b.Navigation("Favorites");

                    b.Navigation("PointsRecords");

                    b.Navigation("QuoteFavorites");

                    b.Navigation("Ratings");

                    b.Navigation("Recitations");
                });

            modelBuilder.Entity("PoemApp.Core.Entities.UserRecitation", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
