// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PoemApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("00000000000000_BaselineInitial")]
    partial class BaselineInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally left empty for baseline
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");
        }
    }
}